### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CodyPChristian** [maros/Zway-WeatherUnderground#1]
Hey, just installed this module and I get the following error after setting it up.

Cannot instantiate module: Zway-WeatherUnderground: TypeError: undefined is not a function

Settings: http://cl.ly/image/17360b2q1m23/Screen%20Shot%202015-10-18%20at%206.55.13%20PM.png

Also where does Zway typically log the full details of these JS errors at?

**Comment by maros** [comment]
Please log in to the host running zway and open the file '/var/log/z-way-server.log' and try to find the error messages. (Running 'tail -n100 -f /var/log/z-way-server.log' while setting up the module should also reveal the detailed error message)

**Comment by CodyPChristian** [comment]
This occurred when trying to add the application.

[2015-10-26 00:24:44.223] [I] [core] Notification: error (core): Cannot instantiate module: Zway-WeatherUnderground: TypeError: undefined is not a function
[2015-10-26 00:24:44.234] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:287:24)
    at AutomationController.createInstance (automation/classes/AutomationController.js:504:14)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:656:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:27:11)

**Comment by maros** [comment]
I believe that this is due to a faulty installation. Judging from the error message you copied the module to /opt/z-way-server/automation/modules/Zway-WeatherUnderground. However it should reside in /opt/z-way-server/automation/modules/WeatherUnderground
Please refer to https://github.com/maros/Zway-WeatherUnderground#installation

**Comment by CodyPChristian** [comment]
That worked, thanks
